LABEL_HIGH_AI = (
    "This content was likely generated by AI. Our analysis found patterns strongly "
    "associated with AI-generated writing, including uniform sentence structure and "
    "consistent vocabulary use. If you created this yourself, you can submit an appeal."
)

LABEL_UNCERTAIN = (
    "We're not sure whether this was written by a person or an AI. Some patterns "
    "in this content are consistent with AI-generated writing, but we don't have "
    "enough confidence to make a definitive call. Creators who wrote this themselves "
    "can submit an appeal."
)

LABEL_HIGH_HUMAN = (
    "This content appears to have been written by a person. Our analysis found "
    "the kind of variation in style, vocabulary, and structure that's typical "
    "of human writing."
)


def get_label(confidence: float) -> dict:
    """
    Map confidence score to label tier and text.
    Thresholds (asymmetric — false positives cost more than false negatives):
      > 0.75  → likely_ai
      0.40-0.75 → uncertain
      < 0.40  → likely_human
    """
    if confidence > 0.75:
        return {"tier": "likely_ai", "text": LABEL_HIGH_AI}
    elif confidence >= 0.40:
        return {"tier": "uncertain", "text": LABEL_UNCERTAIN}
    else:
        return {"tier": "likely_human", "text": LABEL_HIGH_HUMAN}
