import os
import json
import logging

from groq import Groq

logger = logging.getLogger(__name__)

PROMPT = """You are an AI writing detector. Analyze the text and rate how likely it was generated by an AI writing system (not a human).

Scale 0–10:
- 0 = definitely human-written
- 10 = definitely AI-generated

Look for: uniform sentence structure, hedged corporate phrasing like "it is important to note", parallel constructions, absence of personal voice, predictable rhetorical patterns.

Respond with JSON only:
{"score": <integer 0-10>, "rationale": "<one sentence>"}

Text:
"""


def analyze(text: str) -> float:
    """Return a float 0.0–1.0 where 1.0 = confident AI-generated.
    Falls back to 0.5 on any error.
    """
    try:
        client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": PROMPT + text,
                }
            ],
            temperature=0.1,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if raw.startswith("```"):
            lines = raw.splitlines()
            # Drop first line (```json or ```) and last line (```)
            inner = [l for l in lines[1:] if l.strip() != "```"]
            raw = "\n".join(inner).strip()

        data = json.loads(raw)
        score = float(data["score"])
        normalized = score / 10.0
        # Clamp to [0.0, 1.0]
        normalized = max(0.0, min(1.0, normalized))
        return normalized

    except Exception as exc:
        logger.warning("groq_signal.analyze failed: %s — returning 0.5", exc)
        return 0.5
